---
title: "analisis exploratorio"
output: html_document
date: '2022-07-22'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r cars}
getwd()
df_test <- read.csv("test.csv")
df_train<- read.csv("train.csv")
df_test2 <- read.csv("sample_submission.csv")
df_test['SalePrice']<-df_test2$SalePrice
df_train$MasVnrArea[is.na(df_train$MasVnrArea)] <- median(df_train$MasVnrArea, na.rm=TRUE)

```

```{r}
summary(df_train)
```

```{r}
cor(df_train$LotArea, df_train$SalePrice, method = c("pearson", "kendall", "spearman"))
```
```{r}
cor(df_train$LotArea, df_train$PoolArea, method = c("pearson", "kendall", "spearman"))
```
```{r}
cor(df_train$LotArea, df_train$GrLivArea, method = c("pearson", "kendall", "spearman"))
```
```{r}
cor(df_train$LotArea, df_train$TotRmsAbvGrd, method = c("pearson", "kendall", "spearman"))
```

```{r}
cor(df_train$SalePrice, df_train$TotRmsAbvGrd, method = c("pearson", "kendall", "spearman"))
```
```{r}
cor(df_train$SalePrice, df_train$GarageArea, method = c("pearson", "kendall", "spearman"))
```

```{r}
cor(df_train$SalePrice, df_train$GarageCars, method = c("pearson", "kendall", "spearman"))
```
```{r}
cor(df_train$SalePrice, df_train$TotalBsmtSF, method = c("pearson", "kendall", "spearman"))
```

```{r}
cor(df_train$SalePrice, df_train$Fireplaces, method = c("pearson", "kendall", "spearman"))
```
```{r}
cor(df_train$SalePrice, df_train$KitchenAbvGr, method = c("pearson", "kendall", "spearman"))
```

```{r}
cor(df_train$SalePrice, df_train$BedroomAbvGr, method = c("pearson", "kendall", "spearman"))
```


```{r}
cor(df_train$SalePrice, df_train$FullBath, method = c("pearson", "kendall", "spearman"))
```
```{r}
cor(df_train$SalePrice, df_train$PoolArea, method = c("pearson", "kendall", "spearman"))
```
```{r}
cor(df_train$SalePrice, df_train$MasVnrArea, method = c("pearson", "kendall", "spearman"))
```
```{r}
cor(df_train$SalePrice, df_train$GrLivArea, method = c("pearson", "kendall", "spearman"))
```
```{r}
cor(df_train$SalePrice, df_train$EnclosedPorch, method = c("pearson", "kendall", "spearman"))
```
```{r}
cor(df_train$SalePrice, df_train$WoodDeckSF, method = c("pearson", "kendall", "spearman"))
```
```{r}
cor(df_train$SalePrice, df_train$ScreenPorch, method = c("pearson", "kendall", "spearman"))
```

```{r}
cor(df_train$SalePrice, df_train$BsmtUnfSF, method = c("pearson", "kendall", "spearman"))
```
```{r}
cor(df_train$SalePrice, df_train$HalfBath, method = c("pearson", "kendall", "spearman"))
```
```{r}
library(rela)
library(psych)
library(FactoMineR)
library(fpc)
library(factoextra)
library(dplyr)  
```
```{r}
data <- select(df_train, 
               LotArea,
               LotFrontage,
               SalePrice,
               TotRmsAbvGrd,
               GarageArea,
               GarageCars,
               GrLivArea,
               KitchenAbvGr,
               BedroomAbvGr,
               PoolArea,
               EnclosedPorch,
               WoodDeckSF,
               ScreenPorch,
               BsmtUnfSF,
               HalfBath)
summary(data)
```
```{r}
rcor<-cor(data,use = "pairwise.complete.obs")
det(rcor)

```
# el determinante de la matriz es casi 0, lo que indica que multicolinealidad
```{r}
paf_matrix<-paf(as.matrix(data))
paf_matrix$KMO
```
# un KMO del 61% indica que se adecua
```{r}
paf_matrix$Bartlett
```
# un score de Barlett muy alto indica que es adecuado usar PCA
```{r}
compPrincPCA<-PCA(data,ncp=ncol(data), scale.unit = T)
```
```{r}
summary(compPrincPCA)
```

```{r}
fviz_contrib(compPrincPCA, choice = "var", axes = 1, top = 15)
fviz_contrib(compPrincPCA, choice = "var", axes = 2, top = 15)
fviz_contrib(compPrincPCA, choice = "var", axes = 3, top = 15)
fviz_contrib(compPrincPCA, choice = "var", axes = 4, top = 15)
fviz_contrib(compPrincPCA, choice = "var", axes = 5, top = 15)
fviz_contrib(compPrincPCA, choice = "var", axes = 6, top = 15)
fviz_contrib(compPrincPCA, choice = "var", axes = 7, top = 15)
fviz_contrib(compPrincPCA, choice = "var", axes = 8, top = 15)
```

```{r}
install.packages('epiDisplay')
library(epiDisplay)


install.packages('plyr')
library('plyr')
count(df_train, 'HouseStyle') 
tab1(df_train$HouseStyle, sort.group = "decreasing", cum.percent = TRUE)


tab1(df_train$BldgType, sort.group = "decreasing", cum.percent = TRUE)
tab1(df_train$Exterior1st, sort.group = "decreasing", cum.percent = TRUE)
tab1(df_train$Exterior2nd ,sort.group = "decreasing", cum.percent = TRUE)

```

```{r}
count(df_train, 'HouseStyle') 
pie_values<- c(154,14,726,8,11,445,37,65)
pie_labels<-c("1.5Fin","1.5Unf","1Story","2.5Fin","2.5Unf","2Story","SFoyer","SLvl")
pie(pie_values, labels = pie_labels, main="Pie Chart House Styles")

```



